// <auto-generated />
using System;
using GraveyardGISApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraveyardGISApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Contactdetail", b =>
                {
                    b.Property<int>("ContactDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContactDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeceasedDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("DeceasedDetailsId1")
                        .HasColumnType("int(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoteId")
                        .HasColumnType("int(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlotId")
                        .HasColumnType("int(11)");

                    b.HasKey("ContactDetailsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DeceasedDetailsId1" }, "IX_ContactDetails_DeceasedDetailsId1");

                    b.ToTable("contactdetails", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Deceaseddetail", b =>
                {
                    b.Property<int>("DeceasedDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeceasedDetailsId"));

                    b.Property<int>("ContactDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateBuried")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeceasedStatusId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("DoB")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DoD")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoteId")
                        .HasColumnType("int(11)");

                    b.HasKey("DeceasedDetailsId")
                        .HasName("PRIMARY");

                    b.ToTable("deceaseddetails", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Deceasedstatus", b =>
                {
                    b.Property<int>("DeceasedStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeceasedStatusId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeceasedStatusConstant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("DeceasedStatusId")
                        .HasName("PRIMARY");

                    b.ToTable("deceasedstatus", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Maintenancedetail", b =>
                {
                    b.Property<int>("MaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaintenanceStatusId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlotDetailsId")
                        .HasColumnType("int(11)");

                    b.HasKey("MaintId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaintenanceStatusId" }, "IX_MaintenanceDetails_MaintenanceStatusId");

                    b.HasIndex(new[] { "PlotDetailsId" }, "IX_MaintenanceDetails_PlotDetailsId");

                    b.ToTable("maintenancedetails", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Maintenancestatus", b =>
                {
                    b.Property<int>("MaintenanceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintenanceStatusId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MaintenanceStatusConstant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaintenanceStatusId")
                        .HasName("PRIMARY");

                    b.ToTable("maintenancestatus", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<int?>("ContactDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeceasedDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("MaintenanceDetailsMaintId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PlotDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("NoteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContactDetailsId" }, "IX_Notes_ContactDetailsId");

                    b.HasIndex(new[] { "DeceasedDetailsId" }, "IX_Notes_DeceasedDetailsId");

                    b.HasIndex(new[] { "MaintenanceDetailsMaintId" }, "IX_Notes_MaintenanceDetailsMaintId");

                    b.HasIndex(new[] { "PlotDetailsId" }, "IX_Notes_PlotDetailsId");

                    b.HasIndex(new[] { "UserId" }, "IX_Notes_UserId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Paymentdetail", b =>
                {
                    b.Property<int>("PaymentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PaymentDetailsID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentDetailsId"));

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("BalancePaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ContactDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeceasedDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoteId")
                        .HasColumnType("int(11)");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int(11)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int(11)");

                    b.HasKey("PaymentDetailsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContactDetailsId" }, "IX_PaymentDetails_ContactDetailsId");

                    b.HasIndex(new[] { "DeceasedDetailsId" }, "IX_PaymentDetails_DeceasedDetailsId");

                    b.HasIndex(new[] { "PaymentStatusId" }, "IX_PaymentDetails_PaymentStatusId");

                    b.HasIndex(new[] { "PlotId" }, "IX_PaymentDetails_PlotId");

                    b.ToTable("paymentdetails", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Paymentstatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentStatusConstant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentStatusId")
                        .HasName("PRIMARY");

                    b.ToTable("paymentstatus", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Plotdetail", b =>
                {
                    b.Property<int>("PlotDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlotDetailsId"));

                    b.Property<int>("ContactDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeceasedDetailsId")
                        .HasColumnType("int(11)");

                    b.Property<int>("MaintenanceStatusId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NoteId")
                        .HasColumnType("int(11)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SectionId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlotDetailsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContactDetailsId" }, "IX_PlotDetails_ContactDetailsId")
                        .IsUnique();

                    b.HasIndex(new[] { "DeceasedDetailsId" }, "IX_PlotDetails_DeceasedDetailsId");

                    b.HasIndex(new[] { "MaintenanceStatusId" }, "IX_PlotDetails_MaintenanceStatusId");

                    b.HasIndex(new[] { "PlotId" }, "IX_PlotDetails_PlotId");

                    b.HasIndex(new[] { "SectionId" }, "IX_PlotDetails_SectionId");

                    b.ToTable("plotdetails", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SectionConstant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SectionId")
                        .HasName("PRIMARY");

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Contactdetail", b =>
                {
                    b.HasOne("GraveyardGISApp.Data.Entities.Deceaseddetail", "DeceasedDetailsId1Navigation")
                        .WithMany("Contactdetails")
                        .HasForeignKey("DeceasedDetailsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContactDetails_DeceasedDetails_DeceasedDetailsId1");

                    b.Navigation("DeceasedDetailsId1Navigation");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Maintenancedetail", b =>
                {
                    b.HasOne("GraveyardGISApp.Data.Entities.Maintenancestatus", "MaintenanceStatus")
                        .WithMany("Maintenancedetails")
                        .HasForeignKey("MaintenanceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceDetails_MaintenanceStatus_MaintenanceStatusId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Plotdetail", "PlotDetails")
                        .WithMany("Maintenancedetails")
                        .HasForeignKey("PlotDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceDetails_PlotDetails_PlotDetailsId");

                    b.Navigation("MaintenanceStatus");

                    b.Navigation("PlotDetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Note", b =>
                {
                    b.HasOne("GraveyardGISApp.Data.Entities.Contactdetail", "ContactDetails")
                        .WithMany("Notes")
                        .HasForeignKey("ContactDetailsId")
                        .HasConstraintName("FK_Notes_ContactDetails_ContactDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Deceaseddetail", "DeceasedDetails")
                        .WithMany("Notes")
                        .HasForeignKey("DeceasedDetailsId")
                        .HasConstraintName("FK_Notes_DeceasedDetails_DeceasedDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Maintenancedetail", "MaintenanceDetailsMaint")
                        .WithMany("Notes")
                        .HasForeignKey("MaintenanceDetailsMaintId")
                        .HasConstraintName("FK_Notes_MaintenanceDetails_MaintenanceDetailsMaintId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Plotdetail", "PlotDetails")
                        .WithMany("Notes")
                        .HasForeignKey("PlotDetailsId")
                        .HasConstraintName("FK_Notes_PlotDetails_PlotDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notes_User_UserId");

                    b.Navigation("ContactDetails");

                    b.Navigation("DeceasedDetails");

                    b.Navigation("MaintenanceDetailsMaint");

                    b.Navigation("PlotDetails");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Paymentdetail", b =>
                {
                    b.HasOne("GraveyardGISApp.Data.Entities.Contactdetail", "ContactDetails")
                        .WithMany("Paymentdetails")
                        .HasForeignKey("ContactDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentDetails_ContactDetails_ContactDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Deceaseddetail", "DeceasedDetails")
                        .WithMany("Paymentdetails")
                        .HasForeignKey("DeceasedDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentDetails_DeceasedDetails_DeceasedDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Paymentstatus", "PaymentStatus")
                        .WithMany("Paymentdetails")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentDetails_PaymentStatus_PaymentStatusId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Plotdetail", "Plot")
                        .WithMany("Paymentdetails")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentDetails_PlotDetails_PlotId");

                    b.Navigation("ContactDetails");

                    b.Navigation("DeceasedDetails");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Plotdetail", b =>
                {
                    b.HasOne("GraveyardGISApp.Data.Entities.Contactdetail", "ContactDetails")
                        .WithOne("Plotdetail")
                        .HasForeignKey("GraveyardGISApp.Data.Entities.Plotdetail", "ContactDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlotDetails_ContactDetails_ContactDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Deceaseddetail", "DeceasedDetails")
                        .WithMany("Plotdetails")
                        .HasForeignKey("DeceasedDetailsId")
                        .HasConstraintName("FK_PlotDetails_DeceasedDetails_DeceasedDetailsId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Maintenancestatus", "MaintenanceStatus")
                        .WithMany("Plotdetails")
                        .HasForeignKey("MaintenanceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlotDetails_MaintenanceStatus_MaintenanceStatusId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Plotdetail", "Plot")
                        .WithMany("InversePlot")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlotDetails_PlotDetails_PlotId");

                    b.HasOne("GraveyardGISApp.Data.Entities.Section", "Section")
                        .WithMany("Plotdetails")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlotDetails_Section_SectionId");

                    b.Navigation("ContactDetails");

                    b.Navigation("DeceasedDetails");

                    b.Navigation("MaintenanceStatus");

                    b.Navigation("Plot");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Contactdetail", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Paymentdetails");

                    b.Navigation("Plotdetail");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Deceaseddetail", b =>
                {
                    b.Navigation("Contactdetails");

                    b.Navigation("Notes");

                    b.Navigation("Paymentdetails");

                    b.Navigation("Plotdetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Maintenancedetail", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Maintenancestatus", b =>
                {
                    b.Navigation("Maintenancedetails");

                    b.Navigation("Plotdetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Paymentstatus", b =>
                {
                    b.Navigation("Paymentdetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Plotdetail", b =>
                {
                    b.Navigation("InversePlot");

                    b.Navigation("Maintenancedetails");

                    b.Navigation("Notes");

                    b.Navigation("Paymentdetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.Section", b =>
                {
                    b.Navigation("Plotdetails");
                });

            modelBuilder.Entity("GraveyardGISApp.Data.Entities.User", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
