# Generated by Django 6.0.3 on 2026-03-24 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedStatus',
            fields=[
                ('deceased_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('deceased_status_constant', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_status_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_status_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DeceasedStatus',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('maintenance_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_status_constant', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_status_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_status_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MaintenanceStatus',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('maintenance_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_type_constant', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_type_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_type_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MaintenanceType',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('contact_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_details_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_details_modified', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, db_column='NoteID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.notes')),
            ],
            options={
                'db_table': 'ContactDetails',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status_constant', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_status_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_status_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='PlotDetails',
            fields=[
                ('plot_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_id', models.IntegerField()),
                ('row', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(blank=True, max_length=100, null=True)),
                ('niche', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Unknown', 'Unknown')], default='Available', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plots_created', to=settings.AUTH_USER_MODEL)),
                ('maintenance_status', models.ForeignKey(db_column='MaintenanceStatusID', on_delete=django.db.models.deletion.PROTECT, to='index.maintenancestatus')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plots_modified', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, db_column='NoteID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.notes')),
            ],
            options={
                'db_table': 'PlotDetails',
            },
        ),
        migrations.CreateModel(
            name='DeceasedDetails',
            fields=[
                ('deceased_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_buried', models.DateField(blank=True, null=True)),
                ('dob_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dob_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dob_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dod_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dod_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dod_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_modified', to=settings.AUTH_USER_MODEL)),
                ('deceased_status', models.ForeignKey(db_column='DeceasedStatusID', on_delete=django.db.models.deletion.PROTECT, to='index.deceasedstatus')),
                ('note', models.ForeignKey(blank=True, db_column='NoteID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.notes')),
                ('plot', models.ForeignKey(db_column='PlotID', on_delete=django.db.models.deletion.PROTECT, to='index.plotdetails')),
            ],
            options={
                'db_table': 'DeceasedDetails',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_constant', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.AddField(
            model_name='plotdetails',
            name='section',
            field=models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.PROTECT, to='index.section'),
        ),
        migrations.CreateModel(
            name='DeceasedContactMapping',
            fields=[
                ('deceased_contact_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('relationship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_details', models.ForeignKey(db_column='ContactDetailsID', on_delete=django.db.models.deletion.PROTECT, to='index.contactdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_contact_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deceased_contact_modified', to=settings.AUTH_USER_MODEL)),
                ('deceased_details', models.ForeignKey(db_column='DeceasedDetailsID', on_delete=django.db.models.deletion.PROTECT, to='index.deceaseddetails')),
            ],
            options={
                'db_table': 'DeceasedContactMapping',
                'unique_together': {('deceased_details', 'contact_details')},
            },
        ),
        migrations.CreateModel(
            name='PlotContactMapping',
            fields=[
                ('plot_contact_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_details', models.ForeignKey(db_column='ContactDetailsID', on_delete=django.db.models.deletion.PROTECT, to='index.contactdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plot_contact_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plot_contact_modified', to=settings.AUTH_USER_MODEL)),
                ('plot_details', models.ForeignKey(db_column='PlotDetailsID', on_delete=django.db.models.deletion.PROTECT, to='index.plotdetails')),
            ],
            options={
                'db_table': 'PlotContactMapping',
                'unique_together': {('plot_details', 'contact_details')},
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_details', models.ForeignKey(db_column='ContactDetailsID', on_delete=django.db.models.deletion.PROTECT, to='index.contactdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('deceased_details', models.ForeignKey(blank=True, db_column='DeceasedDetailsID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.deceaseddetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_modified', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, db_column='NoteID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.notes')),
                ('payment_status', models.ForeignKey(db_column='PaymentStatusID', on_delete=django.db.models.deletion.PROTECT, to='index.paymentstatus')),
                ('plot', models.ForeignKey(db_column='PlotID', on_delete=django.db.models.deletion.PROTECT, to='index.plotdetails')),
            ],
            options={
                'db_table': 'PaymentDetails',
                'indexes': [models.Index(fields=['plot', 'payment_status'], name='ix_PlotPaymentStatus'), models.Index(fields=['deceased_details'], name='ix_DeceasedDetails'), models.Index(fields=['contact_details'], name='ix_ContactPaymentDetails'), models.Index(fields=['date_paid'], name='ix_DatePaid')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDetails',
            fields=[
                ('maintenance_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_details', models.ForeignKey(blank=True, db_column='ContactDetailsID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.contactdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_modified', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(db_column='MaintenanceTypeID', on_delete=django.db.models.deletion.PROTECT, to='index.maintenancetype')),
                ('note', models.ForeignKey(blank=True, db_column='NoteID', null=True, on_delete=django.db.models.deletion.PROTECT, to='index.notes')),
                ('plot', models.ForeignKey(db_column='PlotID', on_delete=django.db.models.deletion.PROTECT, to='index.plotdetails')),
            ],
            options={
                'db_table': 'MaintenanceDetails',
                'indexes': [models.Index(fields=['plot', 'maintenance_type'], name='ix_PlotMaintenanceDetails')],
            },
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['plot', 'deceased_status'], name='ix_DeceasedPlotStatus'),
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['date_buried'], name='ix_DateBuried'),
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['dob_year'], name='idx_dobyear'),
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['dod_year'], name='idx_dodyear'),
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['plot'], name='idx_deceased_plot'),
        ),
        migrations.AddIndex(
            model_name='deceaseddetails',
            index=models.Index(fields=['zone_id'], name='idx_deceased_zone'),
        ),
        migrations.AlterUniqueTogether(
            name='deceaseddetails',
            unique_together={('plot', 'zone_id')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_constant', 'section_id'], name='ixSectionConstant'),
        ),
        migrations.AddIndex(
            model_name='plotdetails',
            index=models.Index(fields=['maintenance_status'], name='ix_MaintenanceStatus'),
        ),
        migrations.AddIndex(
            model_name='plotdetails',
            index=models.Index(fields=['note'], name='ix_Notes'),
        ),
        migrations.AddIndex(
            model_name='plotdetails',
            index=models.Index(fields=['section'], name='idx_plotdetails_section'),
        ),
        migrations.AddIndex(
            model_name='plotdetails',
            index=models.Index(fields=['plot_id'], name='idx_plotdetails_plot'),
        ),
    ]
