# Generated by Django 6.0.4 on 2026-04-15 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('force_password_change', models.BooleanField(db_column='ForcePasswordChange', default=False)),
                ('is_locked', models.BooleanField(db_column='IsLocked', default=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Basic', 'Basic')], db_column='Role', default='Basic', max_length=50)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive')),
                ('last_login', models.DateField(blank=True, db_column='LastLogin', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='ContactDetailsID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('middle_name', models.CharField(blank=True, db_column='MiddleName', max_length=100, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ContactDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeceasedContactMapping',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='DeceasedContactMappingID', primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(db_column='IsPrimaryContact', default=True)),
                ('relationship_type', models.CharField(blank=True, db_column='RelationshipType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DeceasedContactMapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeceasedDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='DeceasedDetailsID', primary_key=True, serialize=False)),
                ('zone_id', models.IntegerField(db_column='ZoneID', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='MiddleName', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=20, null=True)),
                ('date_buried', models.DateField(blank=True, db_column='DateBuried', null=True)),
                ('dob_year', models.PositiveSmallIntegerField(blank=True, db_column='DOBYear', null=True)),
                ('dob_month', models.PositiveSmallIntegerField(blank=True, db_column='DOBMonth', null=True)),
                ('dob_day', models.PositiveSmallIntegerField(blank=True, db_column='DOBDay', null=True)),
                ('dod_year', models.PositiveSmallIntegerField(blank=True, db_column='DODYear', null=True)),
                ('dod_month', models.PositiveSmallIntegerField(blank=True, db_column='DODMonth', null=True)),
                ('dod_day', models.PositiveIntegerField(blank=True, db_column='DODDay', null=True)),
            ],
            options={
                'db_table': 'DeceasedDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeceasedStatus',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='DeceasedStatusID', primary_key=True, serialize=False)),
                ('deceased_status_constant', models.CharField(db_column='DeceasedStatusConstant', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'DeceasedStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='MaintenanceDetailsID', primary_key=True, serialize=False)),
                ('maintenance_date', models.DateTimeField(blank=True, db_column='MaintenanceDate', null=True)),
            ],
            options={
                'db_table': 'MaintenanceDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='MaintenanceStatusID', primary_key=True, serialize=False)),
                ('maintenance_status_constant', models.CharField(db_column='MaintenanceStatusConstant', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'MaintenanceStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='MaintenanceTypeID', primary_key=True, serialize=False)),
                ('maintenance_type_constant', models.CharField(db_column='MaintenanceTypeConstant', max_length=100, unique=True)),
                ('description', models.CharField(db_column='Description', max_length=255)),
            ],
            options={
                'db_table': 'MaintenanceType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='NoteID', primary_key=True, serialize=False)),
                ('note', models.CharField(db_column='Note', max_length=4000)),
            ],
            options={
                'db_table': 'Notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='PaymentDetailsID', primary_key=True, serialize=False)),
                ('balance_paid', models.DecimalField(db_column='BalancePaid', decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(db_column='BalanceDue', decimal_places=2, default=0, max_digits=10)),
                ('date_paid', models.DateTimeField(blank=True, db_column='DatePaid', null=True)),
            ],
            options={
                'db_table': 'PaymentDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='PaymentStatusID', primary_key=True, serialize=False)),
                ('payment_status_constant', models.CharField(db_column='PaymentStatusConstant', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'PaymentStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotContactMapping',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='PlotContactMappingID', primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(db_column='IsPrimaryContact', default=True)),
            ],
            options={
                'db_table': 'PlotContactMapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='PlotDetailsID', primary_key=True, serialize=False)),
                ('plot_id', models.IntegerField(db_column='PlotID')),
                ('row', models.CharField(blank=True, db_column='Row', max_length=100, null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=100, null=True)),
                ('side', models.CharField(blank=True, db_column='Side', max_length=100, null=True)),
                ('niche', models.CharField(blank=True, db_column='Niche', max_length=100, null=True)),
                ('plot_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied'), ('Unknown', 'Unknown')], db_column='PlotStatus', default='Available', max_length=9)),
                ('is_available', models.BooleanField(db_column='IsAvailable', default=True)),
            ],
            options={
                'db_table': 'PlotDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate', null=True)),
                ('id', models.AutoField(db_column='SectionID', primary_key=True, serialize=False)),
                ('section_constant', models.CharField(db_column='SectionConstant', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Section',
                'managed': False,
            },
        ),
    ]
