# Generated by Django 6.0.4 on 2026-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotReservationHistory',
            fields=[
                ('id', models.AutoField(db_column='PlotReservationHistoryID', primary_key=True, serialize=False)),
                ('cert_number', models.CharField(blank=True, db_column='CertNumber', max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='MiddleName', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('amount_paid', models.DecimalField(db_column='AmountPaid', decimal_places=2, default=0, max_digits=10)),
                ('reserved_by_name', models.CharField(blank=True, db_column='ReservedByName', max_length=200, null=True)),
                ('witness_name', models.CharField(blank=True, db_column='WitnessName', max_length=200, null=True)),
                ('created_date', models.DateTimeField(db_column='CreatedDate')),
            ],
            options={
                'db_table': 'PlotReservationHistory',
                'managed': False,
            },
        ),
    ]
