# Generated by Django 6.0.4 on 2026-09-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0002_contactmessage_newslettersubscriber'),
        ('cemetery', '0002_plotreservationhistory'),
    ]

    operations = [
    ]
